services:
  - type: web
    name: policy-analysis-api
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: HACKRX_TOKEN
        value: my_hackrx_token
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true 